# Generated by Django 3.1 on 2020-08-13 19:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_score',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.DecimalValidator(3, 1), django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='popularity',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.DecimalValidator(3, 1), django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
    ]
